# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.ApiConfigAnnouncement do
  @moduledoc """
  Public Announcement
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :text
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :text => String.t()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.ApiConfigAnnouncement do
  def decode(value, _options) do
    value
  end
end
