# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.ApiConfigEvents do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :distanceClose,
    :distanceFactor,
    :distanceFar,
    :groupDistance,
    :maximumBunchSize,
    :notVisibleFactor,
    :playerOrderBucketSize,
    :playerOrderFactor,
    :slowUpdateFactorThreshold,
    :viewSegmentLength
  ]

  @type t :: %__MODULE__{
          :distanceClose => integer(),
          :distanceFactor => integer(),
          :distanceFar => integer(),
          :groupDistance => integer(),
          :maximumBunchSize => integer(),
          :notVisibleFactor => integer(),
          :playerOrderBucketSize => integer(),
          :playerOrderFactor => integer(),
          :slowUpdateFactorThreshold => integer(),
          :viewSegmentLength => integer()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.ApiConfigEvents do
  def decode(value, _options) do
    value
  end
end
