# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.ApiConfigDownloadUrlList do
  @moduledoc """
  Download links for various development assets.
  """

  @derive [Poison.Encoder]
  defstruct [
    :sdk2,
    :"sdk3-avatars",
    :"sdk3-worlds"
  ]

  @type t :: %__MODULE__{
          :sdk2 => String.t(),
          :"sdk3-avatars" => String.t(),
          :"sdk3-worlds" => String.t()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.ApiConfigDownloadUrlList do
  def decode(value, _options) do
    value
  end
end
