# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.BanGroupMemberRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :userId
  ]

  @type t :: %__MODULE__{
          :userId => String.t()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.BanGroupMemberRequest do
  def decode(value, _options) do
    value
  end
end
