# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.CreateGroupRoleRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :description,
    :isSelfAssignable,
    :permissions
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :isSelfAssignable => boolean() | nil,
          :permissions => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.CreateGroupRoleRequest do
  def decode(value, _options) do
    value
  end
end
