# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.CreateFileVersionRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :signatureMd5,
    :signatureSizeInBytes,
    :fileMd5,
    :fileSizeInBytes
  ]

  @type t :: %__MODULE__{
          :signatureMd5 => String.t(),
          :signatureSizeInBytes => float(),
          :fileMd5 => String.t() | nil,
          :fileSizeInBytes => float() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.CreateFileVersionRequest do
  def decode(value, _options) do
    value
  end
end
