# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.CreateGroupAnnouncementRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :text,
    :imageId,
    :sendNotification
  ]

  @type t :: %__MODULE__{
          :title => String.t(),
          :text => String.t() | nil,
          :imageId => String.t() | nil,
          :sendNotification => boolean() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.CreateGroupAnnouncementRequest do
  def decode(value, _options) do
    value
  end
end
