# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.FavoriteGroup do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :displayName,
    :id,
    :name,
    :ownerDisplayName,
    :ownerId,
    :tags,
    :type,
    :visibility
  ]

  @type t :: %__MODULE__{
          :displayName => String.t(),
          :id => String.t(),
          :name => String.t(),
          :ownerDisplayName => String.t(),
          :ownerId => String.t(),
          :tags => [String.t()],
          :type => VRChat.Model.FavoriteType.t(),
          :visibility => VRChat.Model.FavoriteGroupVisibility.t()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.FavoriteGroup do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:type, :struct, VRChat.Model.FavoriteType, options)
    |> deserialize(:visibility, :struct, VRChat.Model.FavoriteGroupVisibility, options)
  end
end
