# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.FriendStatus do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :incomingRequest,
    :isFriend,
    :outgoingRequest
  ]

  @type t :: %__MODULE__{
          :incomingRequest => boolean(),
          :isFriend => boolean(),
          :outgoingRequest => boolean()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.FriendStatus do
  def decode(value, _options) do
    value
  end
end
