# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.GroupAnnouncement do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :groupId,
    :authorId,
    :title,
    :text,
    :imageId,
    :imageUrl,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :groupId => String.t() | nil,
          :authorId => String.t() | nil,
          :title => String.t() | nil,
          :text => String.t() | nil,
          :imageId => String.t() | nil,
          :imageUrl => String.t() | nil,
          :createdAt => DateTime.t() | nil,
          :updatedAt => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.GroupAnnouncement do
  def decode(value, _options) do
    value
  end
end
