# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.GroupRole do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :groupId,
    :name,
    :description,
    :isSelfAssignable,
    :permissions,
    :isManagementRole,
    :requiresTwoFactor,
    :requiresPurchase,
    :order,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :groupId => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :isSelfAssignable => boolean() | nil,
          :permissions => [String.t()] | nil,
          :isManagementRole => boolean() | nil,
          :requiresTwoFactor => boolean() | nil,
          :requiresPurchase => boolean() | nil,
          :order => integer() | nil,
          :createdAt => DateTime.t() | nil,
          :updatedAt => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.GroupRole do
  def decode(value, _options) do
    value
  end
end
