# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.GroupLimitedMember do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :groupId,
    :userId,
    :isRepresenting
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :groupId => String.t() | nil,
          :userId => String.t() | nil,
          :isRepresenting => boolean() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.GroupLimitedMember do
  def decode(value, _options) do
    value
  end
end
