# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.GroupMyMember do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :groupId,
    :userId,
    :roleIds,
    :managerNotes,
    :membershipStatus,
    :isSubscribedToAnnouncements,
    :visibility,
    :isRepresenting,
    :joinedAt,
    :bannedAt,
    :has2FA,
    :permissions
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :groupId => String.t() | nil,
          :userId => String.t() | nil,
          :roleIds => [VRChat.Model.String.t()] | nil,
          :managerNotes => String.t() | nil,
          :membershipStatus => String.t() | nil,
          :isSubscribedToAnnouncements => boolean() | nil,
          :visibility => String.t() | nil,
          :isRepresenting => boolean() | nil,
          :joinedAt => DateTime.t() | nil,
          :bannedAt => String.t() | nil,
          :has2FA => boolean() | nil,
          :permissions => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.GroupMyMember do
  def decode(value, _options) do
    value
  end
end
