# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.GroupAuditLogEntry do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :created_at,
    :groupId,
    :actorId,
    :actorDisplayname,
    :targetId,
    :eventType,
    :description,
    :data
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :groupId => String.t() | nil,
          :actorId => String.t() | nil,
          :actorDisplayname => String.t() | nil,
          :targetId => String.t() | nil,
          :eventType => String.t() | nil,
          :description => String.t() | nil,
          :data => map() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.GroupAuditLogEntry do
  def decode(value, _options) do
    value
  end
end
