# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.GroupGallery do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :description,
    :membersOnly,
    :roleIdsToView,
    :roleIdsToSubmit,
    :roleIdsToAutoApprove,
    :roleIdsToManage,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :membersOnly => boolean() | nil,
          :roleIdsToView => [VRChat.Model.String.t()] | nil,
          :roleIdsToSubmit => [VRChat.Model.String.t()] | nil,
          :roleIdsToAutoApprove => [VRChat.Model.String.t()] | nil,
          :roleIdsToManage => [VRChat.Model.String.t()] | nil,
          :createdAt => DateTime.t() | nil,
          :updatedAt => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.GroupGallery do
  def decode(value, _options) do
    value
  end
end
