# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.GroupPermission do
  @moduledoc """
  A permission that can be granted to a role in a group.
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :displayName,
    :help,
    :isManagementPermission,
    :allowedToAdd
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :displayName => String.t() | nil,
          :help => String.t() | nil,
          :isManagementPermission => boolean() | nil,
          :allowedToAdd => boolean() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.GroupPermission do
  def decode(value, _options) do
    value
  end
end
