# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.InfoPush do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :isEnabled,
    :releaseStatus,
    :priority,
    :tags,
    :data,
    :hash,
    :createdAt,
    :updatedAt,
    :startDate,
    :endDate
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :isEnabled => boolean(),
          :releaseStatus => VRChat.Model.ReleaseStatus.t(),
          :priority => integer(),
          :tags => [VRChat.Model.String.t()],
          :data => VRChat.Model.InfoPushData.t(),
          :hash => String.t(),
          :createdAt => DateTime.t(),
          :updatedAt => DateTime.t(),
          :startDate => DateTime.t() | nil,
          :endDate => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.InfoPush do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:releaseStatus, :struct, VRChat.Model.ReleaseStatus, options)
    |> deserialize(:data, :struct, VRChat.Model.InfoPushData, options)
  end
end
