# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.InfoPushDataClickable do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :command,
    :parameters
  ]

  @type t :: %__MODULE__{
          :command => String.t(),
          :parameters => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.InfoPushDataClickable do
  def decode(value, _options) do
    value
  end
end
