# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.InstanceShortNameResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :secureName,
    :shortName
  ]

  @type t :: %__MODULE__{
          :secureName => String.t(),
          :shortName => String.t() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.InstanceShortNameResponse do
  def decode(value, _options) do
    value
  end
end
