# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.InstancePlatforms do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :android,
    :standalonewindows
  ]

  @type t :: %__MODULE__{
          :android => integer(),
          :standalonewindows => integer()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.InstancePlatforms do
  def decode(value, _options) do
    value
  end
end
