# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.InviteMessage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :canBeUpdated,
    :id,
    :message,
    :messageType,
    :remainingCooldownMinutes,
    :slot,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :canBeUpdated => boolean(),
          :id => String.t(),
          :message => String.t(),
          :messageType => VRChat.Model.InviteMessageType.t(),
          :remainingCooldownMinutes => integer(),
          :slot => integer(),
          :updatedAt => DateTime.t()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.InviteMessage do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:messageType, :struct, VRChat.Model.InviteMessageType, options)
  end
end
