# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.ModerateUserRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :moderated,
    :type
  ]

  @type t :: %__MODULE__{
          :moderated => String.t(),
          :type => VRChat.Model.PlayerModerationType.t()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.ModerateUserRequest do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:type, :struct, VRChat.Model.PlayerModerationType, options)
  end
end
