# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.PaginatedGroupAuditLogEntryList do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :results,
    :totalCount,
    :hasNext
  ]

  @type t :: %__MODULE__{
          :results => [VRChat.Model.GroupAuditLogEntry.t()] | nil,
          :totalCount => integer() | nil,
          :hasNext => boolean() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.PaginatedGroupAuditLogEntryList do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:results, :list, VRChat.Model.GroupAuditLogEntry, options)
  end
end
