# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.Permission do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :ownerId,
    :data
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :name => String.t(),
          :ownerId => String.t(),
          :data => map() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.Permission do
  def decode(value, _options) do
    value
  end
end
