# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.RespondGroupJoinRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :action
  ]

  @type t :: %__MODULE__{
          :action => String.t() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.RespondGroupJoinRequest do
  def decode(value, _options) do
    value
  end
end
