# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.SentNotification do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :details,
    :id,
    :message,
    :recieverUserId,
    :senderUserId,
    :senderUsername,
    :type
  ]

  @type t :: %__MODULE__{
          :created_at => DateTime.t(),
          :details => String.t(),
          :id => String.t(),
          :message => String.t(),
          :recieverUserId => String.t(),
          :senderUserId => String.t(),
          :senderUsername => String.t() | nil,
          :type => VRChat.Model.NotificationType.t()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.SentNotification do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:type, :struct, VRChat.Model.NotificationType, options)
  end
end
