# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.UnityPackage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :assetUrl,
    :assetUrlObject,
    :assetVersion,
    :created_at,
    :id,
    :platform,
    :pluginUrl,
    :pluginUrlObject,
    :unitySortNumber,
    :unityVersion
  ]

  @type t :: %__MODULE__{
          :assetUrl => String.t() | nil,
          :assetUrlObject => map() | nil,
          :assetVersion => integer(),
          :created_at => DateTime.t() | nil,
          :id => String.t(),
          :platform => String.t(),
          :pluginUrl => String.t() | nil,
          :pluginUrlObject => map() | nil,
          :unitySortNumber => integer() | nil,
          :unityVersion => String.t()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.UnityPackage do
  def decode(value, _options) do
    value
  end
end
