# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.UpdateGroupGalleryRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :description,
    :membersOnly,
    :roleIdsToView,
    :roleIdsToSubmit,
    :roleIdsToAutoApprove,
    :roleIdsToManage
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :description => String.t() | nil,
          :membersOnly => boolean() | nil,
          :roleIdsToView => [String.t()] | nil,
          :roleIdsToSubmit => [String.t()] | nil,
          :roleIdsToAutoApprove => [String.t()] | nil,
          :roleIdsToManage => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.UpdateGroupGalleryRequest do
  def decode(value, _options) do
    value
  end
end
