# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.UpdateAvatarRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :assetUrl,
    :id,
    :name,
    :description,
    :tags,
    :imageUrl,
    :releaseStatus,
    :version,
    :unityPackageUrl
  ]

  @type t :: %__MODULE__{
          :assetUrl => String.t() | nil,
          :id => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :tags => [String.t()] | nil,
          :imageUrl => String.t() | nil,
          :releaseStatus => VRChat.Model.ReleaseStatus.t() | nil,
          :version => float() | nil,
          :unityPackageUrl => String.t() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.UpdateAvatarRequest do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:releaseStatus, :struct, VRChat.Model.ReleaseStatus, options)
  end
end
