# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.UpdateGroupMemberRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :visibility,
    :isSubscribedToAnnouncements,
    :managerNotes
  ]

  @type t :: %__MODULE__{
          :visibility => VRChat.Model.GroupUserVisibility.t() | nil,
          :isSubscribedToAnnouncements => boolean() | nil,
          :managerNotes => String.t() | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.UpdateGroupMemberRequest do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:visibility, :struct, VRChat.Model.GroupUserVisibility, options)
  end
end
