# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.UpdateFavoriteGroupRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :displayName,
    :visibility,
    :tags
  ]

  @type t :: %__MODULE__{
          :displayName => String.t() | nil,
          :visibility => VRChat.Model.FavoriteGroupVisibility.t() | nil,
          :tags => [VRChat.Model.String.t()] | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.UpdateFavoriteGroupRequest do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:visibility, :struct, VRChat.Model.FavoriteGroupVisibility, options)
  end
end
