# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.UpdateGroupRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :shortCode,
    :description,
    :joinState,
    :iconId,
    :bannerId,
    :languages,
    :links,
    :rules,
    :tags
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :shortCode => String.t() | nil,
          :description => String.t() | nil,
          :joinState => VRChat.Model.GroupJoinState.t() | nil,
          :iconId => String.t() | nil,
          :bannerId => String.t() | nil,
          :languages => [String.t()] | nil,
          :links => [String.t()] | nil,
          :rules => String.t() | nil,
          :tags => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: VRChat.Model.UpdateGroupRequest do
  import VRChat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:joinState, :struct, VRChat.Model.GroupJoinState, options)
  end
end
