# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VRChat.Model.WorldMetadata do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :metadata
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :metadata => map()
        }
end

defimpl Poison.Decoder, for: VRChat.Model.WorldMetadata do
  def decode(value, _options) do
    value
  end
end
